import { useEffect, useMemo, useState } from 'react'
import { apiFetch } from '../lib/api'
import { PageHeader } from '../components/PageHeader'

type UserRow={id:number;name:string;email:string;created_at:string;last_login_at:string|null;login_count:number}
export function AdminUsers(){
 const [users,setUsers]=useState<UserRow[]>([]); const [q,setQ]=useState(''); const [loading,setLoading]=useState(true); const [denied,setDenied]=useState(false)
 useEffect(()=>{apiFetch('/api/auth/admin/users').then(async r=>{if(r.status===403){setDenied(true);return null} if(!r.ok) throw new Error('Falha ao carregar usuarios'); return r.json()}).then(j=>{if(j?.success)setUsers(j.data)}).finally(()=>setLoading(false)).catch(()=>setLoading(false))},[])
 const filtered=useMemo(()=>{const s=q.trim().toLowerCase();return s?users.filter(u=>u.name.toLowerCase().includes(s)||u.email.toLowerCase().includes(s)):users},[users,q])
 const returning=users.filter(u=>u.login_count>1).length; const active30=users.filter(u=>u.last_login_at && Date.now()-new Date(u.last_login_at).getTime()<30*86400000).length
 function csv(){const esc=(v:unknown)=>'"'+String(v??'').replace(/"/g,'""')+'"'; const rows=[['Nome','Email','Cadastro','Ultimo acesso','Logins'],...filtered.map(u=>[u.name,u.email,u.created_at,u.last_login_at??'',u.login_count])]; const blob=new Blob(['\ufeff'+rows.map(r=>r.map(esc).join(';')).join('\n')],{type:'text/csv;charset=utf-8'}); const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='btc-radar-usuarios.csv';a.click();URL.revokeObjectURL(a.href)}
 if(denied)return <div className="card p-6 text-dark-text-primary">Area restrita ao administrador.</div>
 return <div className="space-y-6 animate-fade-in"><PageHeader eyebrow="Administracao" title="Usuarios cadastrados" meta="Leads e atividade de acesso" context="ADMIN"/>
  <div className="grid grid-cols-1 md:grid-cols-3 gap-3">{[['Cadastrados',users.length],['Ativos 30d',active30],['Retornaram',returning]].map(([l,v])=><div className="card p-5" key={String(l)}><div className="text-dark-text-muted text-xs">{l}</div><div className="text-dark-text-primary text-2xl font-semibold mt-1">{v}</div></div>)}</div>
  <div className="card p-5 space-y-4"><div className="flex flex-col md:flex-row gap-3 md:items-center md:justify-between"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar nome ou email" className="px-3 py-2.5 bg-dark-bg-hover border border-dark-bg-border rounded-lg text-dark-text-primary text-sm w-full md:max-w-sm"/><button onClick={csv} className="px-4 py-2.5 bg-accent-blue text-white rounded-lg text-sm font-medium">Exportar CSV</button></div>
  {loading?<div className="text-dark-text-dim text-sm py-8">Carregando...</div>:<div className="overflow-x-auto"><table className="w-full text-xs"><thead><tr className="text-left text-dark-text-muted border-b border-dark-bg-border"><th className="py-2 pr-3">Nome</th><th className="py-2 pr-3">Email</th><th className="py-2 pr-3">Cadastro</th><th className="py-2 pr-3">Ultimo acesso</th><th className="py-2 text-right">Logins</th></tr></thead><tbody>{filtered.map(u=><tr key={u.id} className="border-b border-dark-bg-border/50 text-dark-text-primary"><td className="py-3 pr-3 whitespace-nowrap">{u.name}</td><td className="py-3 pr-3"><a href={'mailto:'+u.email} className="text-accent-blue hover:underline">{u.email}</a></td><td className="py-3 pr-3 whitespace-nowrap">{new Date(u.created_at).toLocaleDateString('pt-BR')}</td><td className="py-3 pr-3 whitespace-nowrap">{u.last_login_at?new Date(u.last_login_at).toLocaleString('pt-BR'):'-'}</td><td className="py-3 text-right">{u.login_count}</td></tr>)}</tbody></table></div>}</div></div>
}
